### ISSUE TITLE
Put meaningful badges in READMEs

### ISSUE THREAD

**Issue by qhantom** [Frachtwerk/essencium-frontend#327]
**DESCRIPTION**
To upgrade the `README` files, we could implement some badges that are meaningful like license, pipeline status, deployment status etc.

There are some websites where we can get some badges that fit, like: https://github.com/dwyl/repo-badges

EDIT:
We add and upgrade READMEs in all packages + the one of the monorepo. It would make sense to write a quick explanation of every specific package and the monorepo. Then we could present the docs in the README in a more efficient way because they contain all important information.

Add following badges:
License
Contributors
Pipeline status
Code coverage
Npm package version
We can create static and dynamic badges with [shields.io](http://shields.io/)

**Comment by PhilKsr** [comment]
I would suggest to add and upgrade an `README` file in all packages + the one of the monorepo. It would make sense to write a quick explanation of every specific package and the monorepo. Then we could present the docs in the `README` in a more efficient way because they contain all important information. 

To give an impression of the current state we could add following badges:
- License
- Contributors
- Pipeline status
- Code coverage
- Npm package version

We can create static and dynamic badges with [shields.io](http://shields.io/)

**Comment by qhantom** [comment]
> @qhantom @CathrinTruchan I would suggest to add and upgrade an `README` file in all packages + the one of the monorepo. It would make sense to write a quick explanation of every specific package and the monorepo. Then we could present the docs in the `README` in a more efficient way because they contain all important information.
> 
> To give an impression of the current state we could add following badges:
> 
> * License
> * Contributors
> * Pipeline status
> * Code coverage
> * Npm package version
> 
> We can create static and dynamic badges with [shields.io](http://shields.io/)
> 
> What do you think?

Thanks for your work @PhilKsr 🥳 
Good idea to put READMEs in all packages including the monorepo. I'm also totally fine with the listed badges!
