### ISSUE TITLE
props cancelled error in console

### ISSUE THREAD

**Issue by qhantom** [Frachtwerk/essencium-frontend#485]
**Describe the bug**
Not really a bug but rather a warning.

**To Reproduce**

2. Go to ['Essencium staging'](https://staging.essencium.dev/)
2. Open dev tools and the console tab
3. Maybe you need to refresh the page
4. See the error in the console

**Expected behaviour**
A clear console without errors and warnings.

**Screenshots**
![image](https://github.com/Frachtwerk/essencium-frontend/assets/54100938/d41dd52e-8b3c-4c78-96fd-e13b2d684777)

**Comment by PhilKsr** [comment]
**Waiting for next 14 upgrade.**

Issue is caused because the next router is initial interrupted by a useEffect to set the locale in the `AuthLayout.tsx`. Tested several other ways to set the locale in the router but none of them worked. Only known "fix" is to set a timeout to let the router first load the page and serverside props and then replace the same path with the locale.

We agreed on waiting for the next 14 upgrade and investigate the issue again afterwards. If it still shows up and no proper fix is available we thought about a workaround like catching the error and return an empty object to avoid the thrown error.

**Comment by qhantom** [comment]
@PhilKsr monitored

**Comment by PhilKsr** [comment]
Solved with [App Router migration](https://github.com/Frachtwerk/essencium-frontend/pull/615) 🥳
